//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdDinner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dinner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dinner()
        {
            this.RSVPs = new HashSet<RSVP>();
        }
    
        public int DinnerID { get; set; }
        public string Title { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Description { get; set; }
        public string C_HostedBy { get; set; }
        public string ContractPhone { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSVP> RSVPs { get; set; }
    }
}
